server:
  port: 58080
#  servlet:
#    encoding:
#      charset: UTF-8
#      force: true
#    jsp:
#      init-parameters:
#        development: true

spring:
  profiles:
    active: local
  #  mvc:
  #    view:
  #      prefix: /WEB-INF/views/
  #      suffix: .jsp
  datasource:
    url: jdbc:h2:~/h2db/scm;AUTO_SERVER=TRUE;LOCK_TIMEOUT=10000;TRACE_LEVEL_FILE=0
    driver-class-name: org.h2.Driver
    username: sa
    password:
    #  sql:
    #    init:
    #      mode: always            # 항상 SQL 초기화 실행
    #      schema-locations: classpath:sql/schema.sql  # 스키마 초기화 파일 위치
    #      data-locations: classpath:sql/project_data.sql,classpath:sql/build_data.sql,classpath:sql/projmgmt_data.sql
    hikari:
      maximum-pool-size: 30             # (default : 10)최대 pool size,
      # "Connection is not available, request timed out after ${connection-timeout}ms" 오류 밸상되면 pool locking(deadlock)상태임,
      # HikariCP max pool size 공식 => T * (C - 1) + 1,
      # T = CPU코어 개수(현재 하나의 커넥션에서 처리되는 Thead개수),
      # C = 하나의 트랜젝션에서 최대 사용될 커넥션 개수
      # ex> cpu 물리 코어 개수 = 5, 트랜게션당 최대 커넥션수 = 3 ==> 5 * (3 - 1) + 1 = 11
      connection-timeout: 30000         # (default : 30_000) client가 pool에 connection을 기다리는 최대 시간
      minimum-idle: 10                  # (default : maximum-pool-size와 동일) pool에 유지할 최소 connection 개수(최적의 응답시간을 위해서는 0으로 설정)
      idle-timeout: 600000              # (default : 600_000, 최소값 : 10_000ms) pool에서 유휴상태로 유지 될수 있는 최대 시간, (minimum-idle값이 maximum-pool-size보다 작게 설정된 경우에만 작동함)
      max-lifetime: 1800000             # (default : 1_800_000, 최소값 : 30_000ms) 최대 connection 유지 시간, 이 설정값이 지난 connection은 제거됨
      # "possibly consider using a shorter maxLifeTime value"오류가 발생되면 이 값을 DB의 대기(MySQL의 경우 wait_timeout(default: 28_800/8h)) 시간보다 2~3초 짧게 잡으면 됨
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: PUBLIC
    defer-datasource-initialization: true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  mvc:
    static-path-pattern: /static/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.lottecard: DEBUG
    org.springdoc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.stat: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO