server:
  port: 8090

spring:
  application:
    name: ai-chatbot

  # Spring AI OpenAI 설정
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-api-key-here}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 1000

# 로깅 설정
#logging:
#  level:
#    com.farfarcoder.ai: DEBUG
#    org.springframework.ai: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Swagger 설정
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    operations-sorter: method