management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: [ "info", "health", "refresh", "beans", "configprops", "env", "mappings" ]
  endpoint:
    configprops:
      show-values: when_authorized
  info:
    git:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: step-hts-server
          predicates:
            - Path=/api/hts/**
          uri: http://localhost:18080
          filters:
            - RewritePath=/api/hts/(?<segment>.*), /hts/$\{segment}

tour:
  gateway:
    routes:
      gateway-api:
        - predicates:
            - Path=/api/hts/airflies/{id}
          filters:
            - AuthenticationCheckFilter

  authorization:
    auth-info-map:
      kr:
        client-ip:
          - 0:0:0:0:0:0:0:1
          - 127.0.0.1
      us:
        client-ip:
          - 0:0:0:0:0:0:0:1
          - 127.0.0.1
      jp:
        client-ip:
          - 2.0.0.0/16
