management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include: [ "info", "health", "refresh", "beans", "configprops", "env", "mappings","gateway" ]
  endpoint:
    configprops:
      show-values: when_authorized
  info:
    git:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: step-hts-server
          predicates:
            - Path=
          uri: http://localhost:18080
          filters:
            - RewritePath=/api/hts/(?<segment>.*), /hts/$\{segment}
        - id: tour-server
          predicates:
            - Path=
          uri: http://localhost:38080
          filters:
            - RewritePath=/api/tour/(?<segment>.*), /$\{segment}
        - id: user-server
          predicates:
            - Path=
          uri: http://localhost:28080
          filters:
            - RewritePath=/api/user/(?<segment>.*), /user/$\{segment}

tour:
  gateway:
    routes:
      step-hts-server:
        - predicates:
            - Path=/api/hts/airflies/{id}
      tour-server:
        - predicates:
            - Path=/api/tour/hotels
      user-server:
        - predicates:
            - Path=/api/user/signup
        - predicates:
            - Path=/api/user/login

  authorization:
    auth-info-map:
      kr:
        client-ip:
          - 0:0:0:0:0:0:0:1
          - 127.0.0.1
      us:
        client-ip:
          - 0:0:0:0:0:0:0:1
          - 127.0.0.1
      jp:
        client-ip:
          - 2.0.0.0/16
