
### user 회원가입
POST http://localhost:9999/api/user/signup
accept: */*
Content-Type: application/json

{
  "userId": "renzo1970",
  "name": "leesoonwoo",
  "password": "qwer1234",
  "idType": "REG_NO",
  "idValue": "100"
}

### user 로그인
POST http://localhost:9999/api/user/login
Content-Type: application/json

{
  "userId": "renzo1970",
  "password": "qwer1234"
}

### tour
GET http://localhost:9999/api/tour/hotels
Content-Type: application/json

###