### swagger ui api
GET http://localhost:8888/swagger-ui.html

### 회원가입

POST http://localhost:28080/user/singup
Content-Type: application/json

{
  "userId": "renzo@gmail.com",
  "name": "renzo",
  "password": "renzo123",
  "idType": "REG_NO",
  "idValue": "8012248432142"
}

### 회원 로그인
POST http://localhost:28080/user/login
Content-Type: application/json

{
  "userId": "renzo@gmail.com",
  "password": "renzo123"
}
